# Generated by Django 6.0.1 on 2026-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['refresh_token'], name='accounts_de_refresh_c6c0ca_idx'),
        ),
    ]
