# Generated by Django 6.0.1 on 2026-01-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='allows_premium',
            field=models.BooleanField(default=False),
        ),
    ]
